stages: # List of stages for jobs, and their order of execution.
  - build
  - test

build-job: # Compiles the project
  stage: build
  image: maven:3.9-eclipse-temurin-21-alpine # Docker image running Maven 3.9 with JDK21
  script:
    - echo "Compiling Maven project"
    - mvn clean package -Dskiptests
    - echo "Compile complete"

test:   # Testing 
  stage: test    # Tests only execute if the compile stage is successful. 
  script:
    - echo "Running Unit Tests"
    - mvn test # Run JUnit tests through Maven
    - echo "Test execution Complete"
  artifacts:
    when: always
    expire_in: 30 days
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
