# CI/CD Pipeline for the Frontend React Application, installs app dependencies and builds the application.

stages:
  - build

build-frontend:
  stage: build
  image: node:14 # using Node 14 docker image
  script:
    - cd frontend/dal-social
    - echo "Installing dependencies"
    - npm clean cache --force
    - npm install # install dependencies
    - echo "Dependencies installed"
    - echo "Starting React App"
    - npm run build # build react app
    - echo "Build complete"
